stages:
  - build
  - deploy

build:
  stage: build
  image: docker:git
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker info
    - docker login registry.gitlab.com -u $DOCKER_EMAIL -p $DOCKER_PASSWORD
    - docker pull registry.gitlab.com/meikukb/lensire/client
    - docker build --rm=false -t registry.gitlab.com/meikukb/lensire/client .
    - docker push registry.gitlab.com/meikukb/lensire/client
  only:
    - master
