const en = {
  'waiting_on_products': 'Waiting on products..',
  'header.menu.home': 'Home',
  'header.menu.daily': 'Dailies',
  'header.menu.monthly': 'Monthlies',
  'header.menu.weekly': 'Weekly',
  'header.menu.yearly': 'Yearly',
  'homepage.info': 'Lensire is a contact lens pricing comparison website that compiles prices all over the world and tries to give you the best pricing for any reseller that can ship to you.',
  'homepage.chosen': 'Your chosen country is <strong>{country}</strong> and currency is <strong>{currency}</strong>',
  'homepage.popular_header': 'Popular contact lenses',
  'products.info': 'Here is a list of {type} contact lenses we currently provide pricing for.',
  'footer.by': '<strong>Lensire</strong> by <strong>Meiku</strong>',
  'footer.affiliate': 'Links marked as "Affiliate" are affiliate links and gives us money in return of you buying from there.',
  'footer.general': 'General',
  'footer.general.impressum': 'Impressum',
  'footer.general.about': 'About us',
  'footer.general.contact': 'Contact us',
  'footer.legal': 'Legal',
  'footer.legal.terms': 'Terms and Conditions',
  'footer.legal.privacy_policy': 'Privacy Policy',
  'footer.legal.copyright': 'Copyright',
  'product.manufacturer': 'Manufactured by {company}',
  'product.cheapest_resellers': 'Cheapest resellers',
  'product.sort_by.per_lens': 'Sort price by per lens',
  'product.sort_by.per_box': 'Sort price by per box',
  'product.shipping_prices_included': 'The price per lens and total price has shipping fee included.',
  'pricing.pack': 'Pack of {amount}',
  'pricing.shipping.free': 'Free shipping',
  'pricing.shipping.cost': '{amount} {currency} for shipping',
  'pricing.in_stock': 'In stock',
  'pricing.not_in_stock': 'Not in stock',
  'pricing.per_lens': '{amount} {currency} per lens',
  'pricing.affiliate': 'Affiliate',
  'pricing.per_box': '{amount} {currency} &raquo;',
  'pricing.empty': 'Currently we have no prices for this contact lens. Sorry about that.',
  'product.type.daily': 'Daily contacts',
  'product.type.monthly': 'Monthly contacts',
  'product.type.weekly': 'Weekly contacts',
  'product.type.yearly': 'Yearly contacts',
  'product.type.color': 'Colour',
  'product.type.toric': 'Toric',
  'product.type.spherical': 'Spherical',
  'product.type.multifocal': 'Multifocal',
  'product.type.bifocal': 'Bifocal',
  'product.type.monovision': 'Monovision',
  'product.type.conventional': 'Conventional',
  'product.type.rigid_gas': 'Rigid gas',
  'product.type.permeable': 'Permeable',
  'product.type.hard': 'Hard'
}

export default en
