const sv = {
  'waiting_on_products': 'Väntar på produkter..',
  'header.menu.home': 'Hem',
  'header.menu.daily': 'Endagslinser',
  'header.menu.monthly': 'Månadslinser',
  'header.menu.three_months': '3 Månadslinser',
  'header.menu.weekly': 'Veckolinser',
  'header.menu.biweekly': 'Varannan vecka',
  'header.menu.yearly': 'Årslinser',
  'homepage.info': 'Lensire är en webbplats för jämförelse av kontaktlinser som sammanställer priser över hela världen och försöker ge dig den bästa prissättningen för alla återförsäljare som kan leverera till dig.',
  'homepage.chosen': 'Ditt valda land är <strong>{country}</strong> och valutan <strong>{currency}</strong>',
  'homepage.popular_header': 'Populära kontaktlinser',
  'products.info': 'Här är en lista för {type} kontaktlinser som vi just nu har priser för.',
  'footer.by': '<strong>Lensire</strong> av <strong>Meiku</strong>',
  'footer.affiliate': 'Länkar markerade som "Affiliate" är affiliate länkar och ger oss pengar tillbaka ifall att du köper därifrån.',
  'footer.general': 'Allmänt',
  'footer.general.impressum': 'Impressum',
  'footer.general.about': 'Om oss',
  'footer.general.contact': 'Kontakta oss',
  'footer.legal': 'Legal',
  'footer.legal.terms': 'Villkor',
  'footer.legal.privacy_policy': 'Integritetspolicy',
  'footer.legal.copyright': 'Upphovsrätt',
  'product.manufacturer': 'Tillverkad av {company}',
  'product.cheapest_resellers': 'Billigaste återförsäljare',
  'product.sort_by.per_lens': 'Sortera på pris per lins',
  'product.sort_by.per_box': 'Sortera på pris per box',
  'product.shipping_prices_included': 'Pris för frakt är inkluderat i priserna för per lins och total priset.',
  'pricing.pack': '{amount}-pack',
  'pricing.shipping.free': 'Fri frakt',
  'pricing.shipping.cost': 'Frakt på {amount} {currency}',
  'pricing.in_stock': 'I lager',
  'pricing.not_in_stock': 'Ej i lager',
  'pricing.per_lens': '{amount} {currency} per lins',
  'pricing.affiliate': 'Affiliate',
  'pricing.per_box': '{amount} {currency} &raquo;',
  'product.empty': 'Vi har just nu inga priser för denna lins. Kom tillbaka senare!'
}

export default sv
