const sv = {
  'waiting_on_products': 'Väntar på produkter..',
  'header.menu.home': 'Hem',
  'header.menu.daily': 'Endagslinser',
  'header.menu.monthly': 'Månadslinser',
  'header.menu.weekly': 'Veckolinser',
  'header.menu.yearly': 'Årslinser',
  'homepage.info': 'Lensire är en webbplats för jämförelse av kontaktlinser som sammanställer priser över hela världen och försöker ge dig den bästa prissättningen för alla återförsäljare som kan leverera till dig.',
  'homepage.chosen': 'Ditt valda land är <strong>{country}</strong> och valutan <strong>{currency}</strong>',
  'homepage.popular_header': 'Populära kontaktlinser',
  'products.info': 'Här är en lista för {type} kontaktlinser som vi just nu har priser för.',
  'footer.by': '<strong>Lensire</strong> av <strong>Meiku</strong>',
  'footer.affiliate': 'Länkar markerade som "Affiliate" är affiliate länkar och ger oss pengar tillbaka ifall att du köper därifrån.',
  'footer.general': 'Allmänt',
  'footer.general.impressum': 'Impressum',
  'footer.general.about': 'Om oss',
  'footer.general.contact': 'Kontakta oss',
  'footer.legal': 'Legal',
  'footer.legal.terms': 'Villkor',
  'footer.legal.privacy_policy': 'Integritetspolicy',
  'footer.legal.copyright': 'Upphovsrätt',
  'product.manufacturer': 'Tillverkad av {company}',
  'product.cheapest_resellers': 'Billigaste återförsäljare',
  'product.sort_by.per_lens': 'Pris per lins',
  'product.sort_by.per_box': 'Pris per box',
  'product.shipping_prices_included': 'Pris för frakt är inkluderat i priserna för per lins och total priset.',
  'pricing.pack': '{amount}-pack',
  'pricing.shipping.free': 'Fri frakt',
  'pricing.shipping.cost': '{text} frakt inkl.',
  'pricing.in_stock': 'I lager',
  'pricing.not_in_stock': 'Ej i lager',
  'pricing.per_lens': '{text} per lins',
  'pricing.affiliate': 'Affiliate',
  'product.empty': 'Vi har just nu inga priser för denna lins. Kom tillbaka senare!',
  'product.type.daily': 'Endagslins',
  'product.type.monthly': 'Månadslins',
  'product.type.weekly': 'Veckolins',
  'product.type.yearly': 'Årslins',
  'product.type.color': 'Färglins',
  'product.type.toric': 'Torisk',
  'product.type.spherical': 'Sfärisk',
  'product.type.multifocal': 'Multifokal',
  'product.type.bifocal': 'Bifokal',
  'product.type.monovision': 'Monovision',
  'product.type.conventional': 'Conventional',
  'product.type.rigid_gas': 'Gas',
  'product.type.permeable': 'Permeable',
  'product.type.hard': 'Hård',
  'no_data': 'Just nu så finns det inga produkter i databasen.'
}

export default sv
